pre-commit:
  parallel: true
  jobs:
    - name: format
      run: bun run format {staged_files}
      glob: "*.{js,ts,jsx,tsx,json,md,mdx,css,html,vue,yaml,toml,astro}"
      exclude: "bun.lock"
      stage_fixed: true

    - name: lint
      run: bun run lint

    - name: typecheck
      run: bun run typecheck
